"""Integration checks in a disposable database; existing databases are untouched.

Run from the project root with a PostgreSQL user allowed to CREATE DATABASE:
    python tests/test_road_delivery.py
Uses DATABASE_URL or .streamlit/secrets.toml, and installed project dependencies.
"""

import os
from datetime import date, time
from pathlib import Path
import secrets
import sys
import threading
import tomllib
import unittest

import psycopg
from psycopg import sql
from psycopg.conninfo import conninfo_to_dict, make_conninfo

ROOT = Path(__file__).resolve().parents[1]


class RoadDeliveryTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        url = os.getenv("DATABASE_URL") or tomllib.loads(
            (ROOT / ".streamlit/secrets.toml").read_text()
        )["DATABASE_URL"]
        options = conninfo_to_dict(url)
        options["dbname"] = "postgres"
        cls.admin = psycopg.connect(make_conninfo(**options), autocommit=True)
        cls.database_name = "road_delivery_test_" + secrets.token_hex(8)
        cls.admin.execute(sql.SQL("CREATE DATABASE {}").format(sql.Identifier(cls.database_name)))
        options["dbname"] = cls.database_name
        cls.test_url = make_conninfo(**options)
        cls.addClassCleanup(cls.remove_test_database)
        with psycopg.connect(cls.test_url, autocommit=True) as conn:
            conn.execute((ROOT / "schema/00-schema.sql").read_text())
            conn.execute("INSERT INTO stores (store_name, address) VALUES ('Test hub', 'Kandy')")
            conn.execute("""INSERT INTO routes (store_id, route_name, service_area, max_delivery_time_hrs)
                            VALUES (1, 'Short route', 'Test area', 12), (1, 'Long route', 'Test area', 168)""")
            conn.execute("""INSERT INTO trucks (store_id, license_plate, capacity)
                            SELECT 1, 'TEST-' || n, 100 FROM generate_series(1,4) n""")
            conn.execute("""INSERT INTO employees (store_id, employee_name, employee_role, contact_phone)
                            SELECT 1, 'Driver ' || n, 'DRIVER', '0771234567' FROM generate_series(1,4) n""")
            conn.execute("""INSERT INTO employees (store_id, employee_name, employee_role, contact_phone)
                            SELECT 1, 'Assistant ' || n, 'ASSISTANT', '0771234567' FROM generate_series(1,4) n""")
            conn.execute("""INSERT INTO truck_schedules
                            (truck_id, route_id, driver_id, start_timestamp, end_timestamp)
                            VALUES (1, 1, 1, '2020-01-01 08:00+05:30', '2020-01-02 08:00+05:30')""")
            migration = (ROOT / "schema/06-schedule_delivery.sql").read_text()
            conn.execute(migration)
            conn.execute(migration)
            legacy = conn.execute("SELECT assistant_id, duration_hours FROM truck_schedules").fetchone()
            assert legacy == (None, 24), "Migration changed legacy data"
            conn.execute("DELETE FROM truck_schedules")
        print("Installation, reapplication, and preservation of legacy data: PASS", flush=True)

    @classmethod
    def remove_test_database(cls):
        # The identifier is generated by this test run; never drop a configured database.
        cls.admin.execute(sql.SQL("DROP DATABASE {} WITH (FORCE)").format(sql.Identifier(cls.database_name)))
        cls.admin.close()

    def setUp(self):
        self.conn = psycopg.connect(self.test_url)
        self.conn.execute("SELECT 1")

    def tearDown(self):
        self.conn.rollback()
        self.conn.close()

    def book(self, start="2026-10-05 08:00+05:30", end="2026-10-05 10:00+05:30",
             truck=1, driver=1, assistant=5, route=1, conn=None):
        return (conn or self.conn).execute(
            """INSERT INTO truck_schedules
               (truck_id, route_id, driver_id, assistant_id, start_timestamp, end_timestamp)
               VALUES (%s, %s, %s, %s, %s, %s) RETURNING id""",
            (truck, route, driver, assistant, start, end),
        ).fetchone()[0]

    def rejected(self, action, message=None):
        with self.assertRaises(psycopg.errors.CheckViolation) as caught:
            with self.conn.transaction():
                action()
        if message:
            self.assertIn(message, str(caught.exception))

    def test_crud(self):
        schedule = self.book()
        self.conn.execute("UPDATE truck_schedules SET end_timestamp = '2026-10-05 11:00+05:30' WHERE id = %s", (schedule,))
        self.assertEqual(self.conn.execute("SELECT duration_hours FROM truck_schedules WHERE id = %s", (schedule,)).fetchone()[0], 3)
        self.conn.execute("DELETE FROM truck_schedules WHERE id = %s", (schedule,))
        self.assertEqual(self.conn.execute("SELECT count(*) FROM truck_schedules").fetchone()[0], 0)

    def test_missing_assistant(self):
        self.rejected(lambda: self.book(assistant=None))

    def test_same_person_in_both_roles(self):
        self.rejected(lambda: self.book(assistant=1))

    def test_wrong_driver_role(self):
        self.rejected(lambda: self.book(driver=6), "DRIVER role")

    def test_wrong_assistant_role(self):
        self.rejected(lambda: self.book(assistant=2), "ASSISTANT role")

    def test_invalid_time_windows(self):
        for end in ("2026-10-05 08:00+05:30", "2026-10-05 07:00+05:30"):
            self.rejected(lambda: self.book(end=end))

    def test_route_limit_exact_and_one_second_over(self):
        schedule = self.book(end="2026-10-05 20:00+05:30")
        self.rejected(lambda: self.conn.execute(
            "UPDATE truck_schedules SET end_timestamp = end_timestamp + interval '1 second' WHERE id = %s", (schedule,)),
            "route maximum")

    def test_truck_overlap_across_routes(self):
        self.book()
        self.rejected(lambda: self.book(start="2026-10-05 09:00+05:30", driver=2, assistant=6, route=2), "overlapping")

    def test_driver_overlap_on_different_truck(self):
        self.book()
        self.rejected(lambda: self.book(start="2026-10-05 09:00+05:30", truck=2, assistant=6), "overlapping")

    def test_assistant_overlap_on_different_truck(self):
        self.book()
        self.rejected(lambda: self.book(start="2026-10-05 09:00+05:30", truck=2, driver=2), "overlapping")

    def test_adjacent_truck_with_different_crew_allowed(self):
        self.book()
        self.book(start="2026-10-05 10:00+05:30", end="2026-10-05 11:00+05:30", driver=2, assistant=6)

    def test_driver_consecutive_on_either_side(self):
        self.book()
        self.rejected(lambda: self.book(start="2026-10-05 10:00+05:30", end="2026-10-05 11:00+05:30"), "driver cannot")
        self.rejected(lambda: self.book(start="2026-10-05 07:00+05:30", end="2026-10-05 08:00+05:30"), "driver cannot")

    def test_positive_rest_gap_allowed(self):
        self.book()
        self.book(start="2026-10-05 10:01+05:30", end="2026-10-05 11:00+05:30")

    def test_assistant_two_allowed_three_rejected(self):
        self.book()
        self.book(start="2026-10-05 10:00+05:30", end="2026-10-05 11:00+05:30", driver=2)
        self.rejected(lambda: self.book(start="2026-10-05 11:00+05:30", end="2026-10-05 12:00+05:30", driver=3), "two consecutive")
        self.rejected(lambda: self.book(start="2026-10-05 07:00+05:30", end="2026-10-05 08:00+05:30", driver=3), "two consecutive")

    def test_assistant_insert_between_existing_trips(self):
        self.book(end="2026-10-05 09:00+05:30")
        self.book(start="2026-10-05 10:00+05:30", end="2026-10-05 11:00+05:30", driver=2)
        self.rejected(lambda: self.book(start="2026-10-05 09:00+05:30", end="2026-10-05 10:00+05:30", driver=3), "two consecutive")

    def test_assistant_gap_breaks_chain(self):
        self.book(end="2026-10-05 09:00+05:30")
        self.book(start="2026-10-05 09:00+05:30", end="2026-10-05 10:00+05:30", driver=2)
        self.book(start="2026-10-05 10:01+05:30", end="2026-10-05 11:00+05:30", driver=3)

    def test_driver_40_hour_boundary(self):
        for day in range(5, 10):
            self.book(start=f"2026-10-{day:02} 08:00+05:30", end=f"2026-10-{day:02} 16:00+05:30")
        self.rejected(lambda: self.book(start="2026-10-10 08:00:00+05:30", end="2026-10-10 08:00:01+05:30"), "40-hour")

    def test_assistant_60_hour_boundary(self):
        for i, day in enumerate(range(5, 10)):
            self.book(start=f"2026-10-{day:02} 08:00+05:30", end=f"2026-10-{day:02} 20:00+05:30", driver=i % 4 + 1)
        self.rejected(lambda: self.book(start="2026-10-10 08:00:00+05:30", end="2026-10-10 08:00:01+05:30", driver=3), "60-hour")

    def test_driver_hours_split_at_colombo_week_boundary(self):
        self.conn.execute("SET LOCAL TIME ZONE 'America/New_York'")
        self.book(start="2026-10-05 00:00+05:30", end="2026-10-05 20:00+05:30", route=2)
        self.book(start="2026-10-07 00:00+05:30", end="2026-10-07 19:00+05:30", route=2)
        self.book(start="2026-10-11 23:00+05:30", end="2026-10-12 01:00+05:30")
        self.book(start="2026-10-12 02:00+05:30", end="2026-10-13 17:00+05:30", route=2)
        self.rejected(lambda: self.book(start="2026-10-14 08:00:00+05:30", end="2026-10-14 08:00:01+05:30"), "40-hour")

    def test_assistant_hours_split_at_week_boundary(self):
        self.book(start="2026-10-05 00:00+05:30", end="2026-10-05 20:00+05:30", driver=1, route=2)
        self.book(start="2026-10-07 00:00+05:30", end="2026-10-07 20:00+05:30", driver=2, route=2)
        self.book(start="2026-10-09 00:00+05:30", end="2026-10-09 19:00+05:30", driver=3, route=2)
        self.book(start="2026-10-11 23:00+05:30", end="2026-10-12 01:00+05:30", driver=4)
        self.book(start="2026-10-12 02:00+05:30", end="2026-10-13 18:00+05:30", driver=1, route=2)
        self.book(start="2026-10-14 02:00+05:30", end="2026-10-14 21:00+05:30", driver=2, route=2)
        self.rejected(lambda: self.book(start="2026-10-16 08:00:00+05:30", end="2026-10-16 08:00:01+05:30", driver=3), "60-hour")

    def test_update_cannot_bypass_overlap(self):
        self.book()
        second = self.book(start="2026-10-06 08:00+05:30", end="2026-10-06 10:00+05:30", driver=2, assistant=6)
        self.rejected(lambda: self.conn.execute(
            "UPDATE truck_schedules SET start_timestamp = start_timestamp - interval '1 day', end_timestamp = end_timestamp - interval '1 day' WHERE id = %s", (second,)), "overlapping")

    def test_update_cannot_bypass_weekly_hours(self):
        first = self.book(start="2026-10-05 00:00+05:30", end="2026-10-05 20:00+05:30", route=2)
        self.book(start="2026-10-07 00:00+05:30", end="2026-10-07 20:00+05:30", route=2)
        self.rejected(lambda: self.conn.execute("UPDATE truck_schedules SET end_timestamp = end_timestamp + interval '1 second' WHERE id = %s", (first,)), "40-hour")

    def test_multirow_insert_cannot_bypass_overlap(self):
        self.rejected(lambda: self.conn.execute("""INSERT INTO truck_schedules
            (truck_id, route_id, driver_id, assistant_id, start_timestamp, end_timestamp) VALUES
            (1, 1, 1, 5, '2026-10-05 08:00+05:30', '2026-10-05 10:00+05:30'),
            (1, 1, 2, 6, '2026-10-05 09:00+05:30', '2026-10-05 11:00+05:30')"""), "overlapping")

    def test_multirow_insert_cannot_bypass_weekly_hours(self):
        self.rejected(lambda: self.conn.execute("""INSERT INTO truck_schedules
            (truck_id, route_id, driver_id, assistant_id, start_timestamp, end_timestamp) VALUES
            (1, 2, 1, 5, '2026-10-05 00:00+05:30', '2026-10-05 16:00+05:30'),
            (1, 2, 1, 5, '2026-10-07 00:00+05:30', '2026-10-07 16:00+05:30'),
            (1, 2, 1, 5, '2026-10-09 00:00+05:30', '2026-10-09 16:00+05:30')"""), "40-hour")

    def test_route_edit_cannot_invalidate_schedule(self):
        self.book()
        self.rejected(lambda: self.conn.execute("UPDATE routes SET max_delivery_time_hrs = 1 WHERE id = 1"), "route maximum")

    def test_employee_role_edit_cannot_invalidate_schedule(self):
        self.book()
        self.rejected(lambda: self.conn.execute("UPDATE employees SET employee_role = 'ASSISTANT' WHERE id = 1"), "DRIVER role")
        self.rejected(lambda: self.conn.execute("UPDATE employees SET employee_role = 'DRIVER' WHERE id = 5"), "ASSISTANT role")

    def test_assistant_deletion_cannot_leave_schedule_without_crew(self):
        self.book()
        self.rejected(lambda: self.conn.execute("DELETE FROM employees WHERE id = 5"))

    def test_procedure_uses_same_validation(self):
        self.conn.execute("CALL schedule_delivery(1, 1, 1, 5, '2026-10-05 08:00+05:30', '2026-10-05 10:00+05:30')")
        self.rejected(lambda: self.conn.execute("CALL schedule_delivery(1, 1, 2, 6, '2026-10-05 09:00+05:30', '2026-10-05 11:00+05:30')"), "overlapping")

    def concurrent_attempt(self, isolation, overlapping=False):
        first = psycopg.connect(self.test_url)
        second = psycopg.connect(self.test_url)
        started = threading.Event()
        finished = threading.Event()
        result = []
        try:
            second.execute(sql.SQL("SET TRANSACTION ISOLATION LEVEL {}").format(sql.SQL(isolation)))
            second.execute("SELECT count(*) FROM truck_schedules")
            self.book(start="2026-10-05 00:00+05:30", end="2026-10-05 20:00+05:30", route=2, conn=first)

            def attempt():
                started.set()
                try:
                    self.book(start="2026-10-05 01:00+05:30" if overlapping else "2026-10-07 00:00+05:30",
                              end="2026-10-05 03:00+05:30" if overlapping else "2026-10-08 06:00+05:30",
                              route=2, conn=second)
                    second.commit()
                    result.append("accepted")
                except psycopg.Error as error:
                    second.rollback()
                    result.append(error.sqlstate)
                finally:
                    finished.set()

            thread = threading.Thread(target=attempt, daemon=True)
            thread.start()
            self.assertTrue(started.wait(2))
            self.assertFalse(finished.wait(0.2), "Concurrent writer bypassed the validation lock")
            first.commit()
            self.assertTrue(finished.wait(5), "Concurrent validation did not finish")
            thread.join(1)
            self.assertEqual(result, ["23514"] if isolation == "READ COMMITTED" else ["40001"])
        finally:
            first.close()
            second.close()
            with psycopg.connect(self.test_url) as cleanup:
                cleanup.execute("DELETE FROM truck_schedules")

    def test_concurrent_overlapping_bookings(self):
        self.concurrent_attempt("READ COMMITTED", overlapping=True)

    def test_concurrent_weekly_hours(self):
        self.concurrent_attempt("READ COMMITTED")

    def test_repeatable_read_stale_writer_retries(self):
        self.concurrent_attempt("REPEATABLE READ")

    def test_serializable_stale_writer_retries(self):
        self.concurrent_attempt("SERIALIZABLE")

    def test_ui_create_read_edit_delete_and_validation(self):
        from streamlit.testing.v1 import AppTest

        sys.path.insert(0, str(ROOT / "app"))
        old_url = os.environ.get("DATABASE_URL")
        os.environ["DATABASE_URL"] = self.test_url
        try:
            # AppTest does not reproduce browser dialog-fragment submissions.
            # Render the real dialog bodies inline to test their forms and CRUD.
            script = (
                "import runpy\nimport streamlit as st\n"
                f"page = runpy.run_path({str(ROOT / 'app/routes/4_Last_Mile_Road_Delivery.py')!r})\n"
                "action = st.session_state.get('road_delivery_test_action')\n"
                "if action == 'create': page['create_schedule_dialog'].__wrapped__()\n"
                "elif action == 'edit': page['edit_schedule_dialog'].__wrapped__(st.session_state['road_delivery_test_id'])\n"
                "elif action == 'delete': page['delete_schedule_dialog'].__wrapped__(st.session_state['road_delivery_test_id'])\n"
            )
            at = AppTest.from_string(script, default_timeout=10)
            # Streamlit exports TOML secrets to environment variables. Supply
            # isolated secrets as well as the URL so it cannot select the app DB.
            at.secrets["DATABASE_URL"] = self.test_url
            at.run()
            self.assertFalse(at.exception, [e.message for e in at.exception])
            self.assertEqual(len(at.dataframe[0].value), 0)
            at.session_state["road_delivery_test_action"] = "create"
            at.run()
            self.assertFalse(at.exception, [e.message for e in at.exception])

            def fill_create_form():
                at.selectbox(key="schedule_create_route").set_value(1)
                at.date_input(key="schedule_create_start_date").set_value(date(2026, 10, 5))
                at.date_input(key="schedule_create_end_date").set_value(date(2026, 10, 5))
                at.time_input(key="schedule_create_start_time").set_value(time(8))
                at.time_input(key="schedule_create_end_time").set_value(time(10))

            fill_create_form()
            next(b for b in at.button if b.label == "Create Schedule").click().run()
            self.assertFalse(at.exception, [e.message for e in at.exception])
            self.assertEqual(self.conn.execute("SELECT count(*) FROM truck_schedules").fetchone()[0], 1,
                             [e.value for e in at.error])
            at.session_state["road_delivery_test_action"] = None
            at.run()
            self.assertEqual(len(at.dataframe[0].value), 1, [e.value for e in at.error])
            schedule_id = int(at.dataframe[0].value.iloc[0]["id"])

            # A duplicate booking must show the database validation error and
            # leave the saved schedule unchanged.
            at.session_state["road_delivery_test_action"] = "create"
            at.run()
            fill_create_form()
            next(b for b in at.button if b.label == "Create Schedule").click().run()
            self.assertFalse(at.exception, [e.message for e in at.exception])
            self.assertTrue(any("overlapping" in e.value for e in at.error))
            self.assertEqual(self.conn.execute("SELECT count(*) FROM truck_schedules").fetchone()[0], 1)

            at.session_state["road_delivery_test_id"] = schedule_id
            at.session_state["road_delivery_test_action"] = "edit"
            at.run()
            self.assertFalse(at.exception, [e.message for e in at.exception])
            at.time_input(key=f"schedule_edit_{schedule_id}_end_time").set_value(time(11))
            next(b for b in at.button if b.label == "Save Changes").click().run()
            self.assertFalse(at.exception, [e.message for e in at.exception])
            at.session_state["road_delivery_test_action"] = None
            at.run()
            self.assertEqual(at.dataframe[0].value.iloc[0]["duration_hours"], 3)

            # A linked item must prevent UI deletion rather than be removed by
            # the existing schema's cascading schedule foreign key.
            customer_id = self.conn.execute("""INSERT INTO customers
                (customer_name, address, contact_phone) VALUES ('Test customer', 'Test address', '0771234567')
                RETURNING id""").fetchone()[0]
            product_id = self.conn.execute("""INSERT INTO products
                (product_name, unit_price, space_consumption_unit) VALUES ('Test product', 10, 1)
                RETURNING id""").fetchone()[0]
            order_id = self.conn.execute("""INSERT INTO orders
                (customer_id, route_id, delivery_address, contact_phone, order_date, delivery_date)
                VALUES (%s, 1, 'Test address', '0771234567', '2026-09-20', '2026-10-05') RETURNING id""",
                (customer_id,)).fetchone()[0]
            item_id = self.conn.execute("""INSERT INTO order_items
                (order_id, product_id, unit_price, quantity) VALUES (%s, %s, 10, 1) RETURNING id""",
                (order_id, product_id)).fetchone()[0]
            self.conn.execute("INSERT INTO truck_item_deliveries (truck_schedule_id, order_item_id) VALUES (%s, %s)",
                              (schedule_id, item_id))
            self.conn.commit()
            at.session_state["road_delivery_test_action"] = "delete"
            at.run()
            next(b for b in at.button if b.label == "Confirm Delete").click().run()
            self.assertFalse(at.exception, [e.message for e in at.exception])
            self.assertTrue(any("assigned delivery items" in e.value for e in at.error))
            self.assertEqual(self.conn.execute("SELECT count(*) FROM truck_item_deliveries").fetchone()[0], 1)
            self.conn.execute("DELETE FROM truck_item_deliveries WHERE truck_schedule_id = %s", (schedule_id,))
            self.conn.commit()
            next(b for b in at.button if b.label == "Confirm Delete").click().run()
            self.assertFalse(at.exception, [e.message for e in at.exception])
            at.session_state["road_delivery_test_action"] = None
            at.run()
            self.assertEqual(len(at.dataframe[0].value), 0)
        finally:
            if old_url is None:
                os.environ.pop("DATABASE_URL", None)
            else:
                os.environ["DATABASE_URL"] = old_url
            with psycopg.connect(self.test_url) as cleanup:
                cleanup.execute("DELETE FROM truck_schedules")


if __name__ == "__main__":
    unittest.main(verbosity=2)
